<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.celements</groupId>
  <artifactId>celements-parent-poms</artifactId>
  <version>7.1</version>
  <packaging>pom</packaging>
  <description>Celements parent POM aggregator</description>
  <modules>
    <module>celements-bom</module>
    <module>celements-parent</module>
  </modules>
  <scm>
    <connection>scm:git:git://github.com/celements/parent-poms</connection>
    <developerConnection>scm:git:git@github.com:celements/parent-poms.git</developerConnection>
    <url>https://github.com/celements/parent-poms</url>
    <tag>celements-parent-poms-7.1</tag>
  </scm>
  <organization>
    <name>synventis gmbh</name>
    <url>https://www.synventis.com</url>
  </organization>
  <distributionManagement>
    <snapshotRepository>
      <id>celements-forge</id>
      <url>${repo.url.dist.celements}</url>
    </snapshotRepository>
    <repository>
      <id>celements-forge</id>
      <url>${repo.url.dist.celements}</url>
    </repository>
  </distributionManagement>
</project>
